### ISSUE TITLE
Introduction to PKPDsim

### ISSUE THREAD

**Issue by ronkeizer** [isop-phmx/studyGroup#15]
Event Proposal: Introduction to PKPDsim

Please tag your issue 'PROPOSAL' and make sure to include the following:

If you would like to present on a topic please fill out the following:
- General Topic: PKPDsim, a library for simulation of systems of differential equations in the pharmacometric setting
- Potential Presenter(s): Ron Keizer
- Potential Date(s): Apr 29, May 13
- Location: SF, CA
- Time: 9am PT, noon EST
- Webcast: http://www.youtube.com/watch?v=9JNW3YZ3f9k
- Background Resources for the Audience: https://github.com/ronkeizer/PKPDsim, www.pkpdsim-docs.com

**Comment by vjd** [comment]
@ronkeizer just following up if I can put this up on the calendar?

**Comment by ronkeizer** [comment]
yup, fine with me

**Comment by kylebaron** [comment]
Does the study group homepage say May 29, 2016 (Sunday)?

**Comment by vjd** [comment]
@kylebmetrum its a mistake.. just making some changes and adding a google calendar api.. will correct the dates. Thanks

**Comment by ronkeizer** [comment]
http://www.youtube.com/watch?v=9JNW3YZ3f9k

**Comment by vjd** [comment]
Great deminar Ron! Look forward to more!
