### ISSUE TITLE
Introduction to mrgsolve

### ISSUE THREAD

**Issue by vjd** [isop-phmx/studyGroup#20]
- General Topic: Introduction to mrgsolve
- Potential Presenter(s): Kyle Baron @kylebmetrum 
- Potential Date(s): TBD
- Location: Online
- Time: TBD
- Background Resources for the Audience: https://github.com/metrumresearchgroup/mrgsolve

How about a short intro to mrgsolve @kylebmetrum?

**Comment by kylebaron** [comment]
Sure;  let me find a date.

**Comment by kylebaron** [comment]
Sure ... let me find a date.

**Comment by kylebaron** [comment]
How about May 13?

**Comment by kylebaron** [comment]
And there is a user guide here: [http://mrgsolve.github.io/user_guide/](http://mrgsolve.github.io/user_guide/)

**Comment by vjd** [comment]
That works. Can you update the issue with date and time and I will push this through to the website.

**Comment by vjd** [comment]
@kylebmetrum can I close this issue as you opened #24 ?

**Comment by kylebaron** [comment]
Yes.
