### ISSUE TITLE
Introduction to Command Line (windows and unix/mac)

### ISSUE THREAD

**Issue by vjd** [isop-phmx/studyGroup#3]
- What: Introduction Command Line (windows and unix/mac)
- When: Friday, April 1, 13:00 (EST)
- Where: UMB Main Campus, Pharmacy Hall N515
- Who: absolutely everyone! Beginners especially welcome!
- Webcast link: TBD, check back a couple minutes before we kick off!

**Comment by wilsonmichaelc** [comment]
https://plus.google.com/events/chs79jiteo7r12ha1cbh7vd1gt0

**Comment by vjd** [comment]
Completed session on youtube - https://www.youtube.com/watch?v=T3euH6UNWqA
Notes associated with the session - https://github.com/wilsonmichaelc/command-line-tutorial

Please feel free to contribute to the notes
