### ISSUE TITLE
Project workflow in pharmacometrics (NONMEM & Phoenix)

### ISSUE THREAD

**Issue by vjd** [isop-phmx/studyGroup#5]
- What: Project workflow in pharmacometrics
- When: Friday, April 15, 1 PM
- Where: UMB Main Campus, Pharmacy Hall N515
- Who: absolutely everyone! Beginners especially welcome!
- Webcast link: TBD, check back a couple minutes before we kick off!

**Comment by krinaj** [comment]
Hi Vijay,

Do you by chance have recording for this? I am particularly interested in NONMEM.

Thanks,
Krina
